### ISSUE TITLE
Create a Basic Home page layout

### ISSUE THREAD

**Issue by shubhkr** [shubhkr/medico#4]
We need to come up with a home page layout which is acceptable and scalable so as to facilitate in building complete functionality.

**Comment by HimachalLad** [comment]
What kind of functionalities are expected out of homepage. We need some documentation regarding the client.

**Comment by shubhkr** [comment]
Yup @piyushbitt  share the doc with @HimachalLad  as well which has the basics.

**Comment by HimachalLad** [comment]
I am not sure about page rank. I think we have to pay for it.

**Comment by sksbtps** [comment]
We cant pay for page rank as per say and even though if we wanted to pay google wont accept it coz it's illegal. One option is to pay for ad when user searches for some specific keywords. Even this is not needed coz we need to make sure that, when someone searches for dentist in area say dumduma then only it needs to be there. 
What i am trying to say is, piyush's dental clinic is not worldwide. Its only one and in a single area. So, we have to make sure to put keywords in our home page and about page such that, when google's crawler crawl's our site, it gets those keywords which people might use to search for dental clinic around them.
eg dental near dumduma So, since we will have these keywords, automatically if they use dumduma in keyword our website will show up on top

**Comment by shubhkr** [comment]
We cant pay for page rank as per say and even though if we wanted to pay google wont accept it coz it's illegal. One option is to pay for ad when user searches for some specific keywords. Even this is not needed coz we need to make sure that, when someone searches for dentist in area say dumduma then only it needs to be there.
What i am trying to say is, piyush's dental clinic is not worldwide. Its only one and in a single area. So, we have to make sure to put keywords in our home page and about page such that, when google's crawler crawl's our site, it gets those keywords which people might use to search for dental clinic around them.
eg dental near dumduma So, since we will have these keywords, automatically if they use dumduma in keyword our website will show up on top

**Comment by piyushbitt** [comment]
Yup, We have to put keyword relevant to the customers search requirements i.e. words that users generally use to search.
